on: [ push ]

jobs:
  verify:
    strategy:
      matrix:
        os: ["windows-2022", "ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./gradlew build
          unzip -l build/libs/not-reproducible-build.jar
