on:
  - push

jobs:
  verify:
    runs-on: ["windows-2022", "ubuntu-20.04"]
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./gradlew build
          unzip -l build/libs/not-reproducible-build.jar
